import{a as y,S as p,i as d}from"./assets/vendor-D8_O3--j.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g=({tags:o,webformatURL:r,largeImageURL:s,likes:l,views:e,comments:t,downloads:n})=>`
      <li>
      <a class="gallery-item" href="${s}">
      <img class="gallery-image" src="${r}" alt="${o}" title="${o}"/>
      <div class="gallery-text-block">
      <p class="gallery-text">Likes<br>${l}</p>
      <p class="gallery-text">Views<br>${e}</p>
      <p class="gallery-text">Comments<br>${t}</p>
      <p class="gallery-text">Downloads<br>${n}</p>
      </div>
      </a>
      </li>
    `;y.defaults.baseURL="https://pixabay.com/api/";const f=async(o,r)=>{const s=new URLSearchParams({q:o,per_page:15,page:r,image_type:"photo",orientation:"horizontal",safesearch:!0,key:"50720550-abdb0a32f459975af0b381b86"});return(await y.get("",{params:s})).data},a={searchForm:document.querySelector(".js-search-form"),gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".js-load-more")};let i=1,c="",u=0;const h=new p(".js-gallery a"),L=async o=>{try{o.preventDefault();const{target:r}=o;if(c=r.elements.user_query.value.trim(),!c)return;i=1,a.loader.classList.add("active"),a.gallery.innerHTML="",a.loadMoreBtn.classList.add("is-hidden"),a.loadMoreBtn.removeEventListener("click",m);const s=await f(c,i);if(a.loader.classList.remove("active"),s.totalHits===0||s.hits.length===0){d.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),a.gallery.innerHTML="";return}u=Math.ceil(s.totalHits/15);const l=s.hits.map(e=>g(e)).join("");a.gallery.innerHTML=l,h.refresh(),i<u?(a.loadMoreBtn.classList.remove("is-hidden"),a.loadMoreBtn.addEventListener("click",m)):d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(r){console.log(r)}};a.searchForm.addEventListener("submit",L);const m=async()=>{try{i++;const r=(await f(c,i)).hits.map(l=>g(l)).join("");a.gallery.insertAdjacentHTML("beforeend",r),h.refresh();const{height:s}=document.querySelector(".js-gallery li").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),i>=u&&(a.loadMoreBtn.classList.add("is-hidden"),a.loadMoreBtn.removeEventListener("click",m),d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(o){console.log(o)}};
//# sourceMappingURL=index.js.map
